[package]
name = "alle-server"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "alle_server"
path = "src/lib.rs"

[[bin]]
name = "alle-server"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = [ "full" ] }
sea-orm = { version = "1.1", features = ["sqlx-sqlite", "sqlx-postgres", "sqlx-mysql", "runtime-tokio-rustls", "macros"] }
sea-orm-migration = { version = "1.1", features = ["sqlx-sqlite", "sqlx-postgres", "sqlx-mysql", "runtime-tokio-rustls"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-graphql = "7.0"
utoipa = { version = "5.3", features = ["chrono"] }
utoipa-swagger-ui = { version = "8.0" }
dotenvy = "0.15.7"
axum = "0.8.8"
async-graphql-axum = "7.1.0"
tower-http = { version = "0.6.8", features = ["cors", "fs"] }
tokio-stream = { version = "0.1.18", features = ["sync"] }
futures-util = "0.3.31"
rust-s3 = { version = "0.35", default-features = false, features = ["tokio-rustls-tls"] }
tokio-util = { version = "0.7", features = ["io"] }
bytes = "1.5"
mime = "0.3"
uuid = { version = "1.0", features = ["v4", "serde"] }

[dev-dependencies]
testcontainers = "0.23"
testcontainers-modules = { version = "0.11", features = ["postgres", "mysql"] }
reqwest = { version = "0.12", features = ["json"] }
serde_json = "1.0"
